name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest
        cd time_based_storage && pip install -e .
    
    - name: Check code formatting with black
      run: |
        black time_based_storage/src time_based_storage/tests --check
    
    - name: Lint with flake8
      run: |
        flake8 time_based_storage/src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 time_based_storage/tests --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 time_based_storage/src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        flake8 time_based_storage/tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run tests
      run: |
        cd time_based_storage && python -m pytest tests/ -v 